package uk.co.mcksn.events.behavior.common.enumeration;

public enum AbstractWhenPlotBehaviorEnumeration {
	SHOULD_wait_for_event_to_occur_WHEN_when_event_GIVEN_event_can_be_waited_for,

	SHOULD_wait_for_multiple_events_to_occur_WHEN_when_events_verify_all_events_GIVEN_events_consist_of_multiple_and,

	SHOULD_wait_for_multiple_events_to_occur_WHEN_when_events_verify_all_events_GIVEN_events_consist_of_multiple_or,

	SHOULD_wait_for_multiple_events_to_occur_WHEN_when_events_verify_all_events_GIVEN_events_consist_of_multiple_and_with_or;

	public static class Constant {

		public static final String SHOULD_wait_for_event_to_occur_WHEN_when_event_GIVEN_event_can_be_waited_for = 
				"SHOULD_wait_for_event_to_occur_WHEN_when_event_GIVEN_event_can_be_waited_for",

		SHOULD_wait_for_multiple_events_to_occur_WHEN_when_events_verify_all_events_GIVEN_events_consist_of_multiple_and = 
		"SHOULD_wait_for_multiple_events_to_occur_WHEN_when_events_verify_all_events_GIVEN_events_consist_of_multiple_and",

		SHOULD_wait_for_multiple_events_to_occur_WHEN_when_events_verify_all_events_GIVEN_events_consist_of_multiple_or = 
		"SHOULD_wait_for_multiple_events_to_occur_WHEN_when_events_verify_all_events_GIVEN_events_consist_of_multiple_or",

		SHOULD_wait_for_multiple_events_to_occur_WHEN_when_events_verify_all_events_GIVEN_events_consist_of_multiple_and_with_or = 
		"SHOULD_wait_for_multiple_events_to_occur_WHEN_when_events_verify_all_events_GIVEN_events_consist_of_multiple_and_with_or";

	}


}
